"""
Event Type Categories Mapping

This module provides a mapping from individual event types to their overarching categories.
Each specific event type is mapped to a broader category that groups related events together.
"""

EVENT_TYPE_CATEGORIES = {
    "physical attack": [
        "actual physical attack",
        "copper theft",
        "copper wire theft",
        "physical attack",
        "physical attack",
        "physcial attack",  # typo in source data
        "potential physical attack",
        "sabatoge",  # typo in source data
        "sabotage",
        "suspected physical attack",
        "theft",
        "threat of physical attack",
        "vandalism",
        "vandalism & sabotage",
    ],
    "cyber attack": [
        "cyber attack",
        "cyber event",
        "cyber event with potential to cause impact",
        "cyber event (information technology)",
        "suspected cyber attack",
    ],
    "severe weather": [
        "cold",
        "earthquake",
        "fog",
        "hail storm",
        "hailstorm",
        "heatwave",
        "heavy winds",
        "high winds",
        "ice",
        "ice and snow storm",
        "lightning",
        "lightning strike",
        "sever weather",  # typo in source data
        "snow",
        "storms and wind",
        "thunderstorms",
        "tornadoes",
        "tornados",
        "weather",
        "weather or natural disaster",
        "weather or natural disaster",
        "wild fires",
        "wind",
        "wind storm",
        "winter",
        "winter storm",
        "winter storm nemo",
    ],
    "fuel supply issues": [
        "coal",
        "fuel supply deficiency",
        "fuel supply emergencies (coal)",
        "fuel supply emergency",
        "fuel supply emergency (natural gas & fuel oil)",
        "fuel supply emergency (natural gas)",
        "fuel supply emergency due to severe weather",
        "fuel supply emergency",
        "hydro",
        "natural gas",
        "petroleum",
    ],
    "generation & equipment failure": [
        "equipment failure",
        "equipment fault",
        "equipment trip & failure",
        "generation inadequacy",
        "generator trip",
        "generator loss or failure",
        "line and generator trip",
    ],
    "power system events": [
        "actual physical event",
        "distribution interruption",
        "electrical system islanding",
        "electrical system separation (islanding",
        "electrical system separation (islanding)",
        "failure at high voltage substation or switchyard",
        "islanding",
        "load shed",
        "load shed 100+ mw",
        "load shed 100+mw",
        "load shed 100+mw due to severe weather",
        "load shed of 100 mw",
        "load shed of 100+ mw",
        "load shed of 100+ mw under emergency operational policy",
        "load shedding of 100 megawatts",
        "loss of 300+ mw load",
        "loss of part of a high voltage substation",
        "loss of power from wholesale provider",
        "major distribution disruption",
        "operational failure of electrical system",
        "public appeal",
        "public appeal due to severe weather",
        "public appeal to reduce electricity usage",
        "system",
        "system operations",
        "system wide voltage reduction",
        "transmission disruption",
        "transmission interruption",
        "transmission system interruption",
        "transmisison interruption",
        "transmission equipment failure",
        "uncontrolled loss of 300 megawatts",
        "voltage reduction",
        "voltage reduction due to severe weather",
        "wide voltage reductions of 3 percent or more",
    ],
    "other/unknown": [
        "operator action(s)",
        "other",
        "suspicious activity",
        "suspicious activity",
        "suspcious activity",  # typo in source data
        "unknown",
        "unknown cause",
    ],
}
